version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./Docker/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    depends_on:
      - db
    volumes:
      - ./resources:/app/resources
      - ./output:/app/output
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: database

  tests:
    build:
      context: .
      dockerfile: Docker/Dockerfile.tests
    depends_on:
      - db
    volumes:
      - ./resources:/app/resources
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: database
volumes:
  volume_postgres:
