FROM python:3.8

WORKDIR /tests

COPY requirements-test.txt .

RUN pip install --no-cache-dir -r requirements-test.txt

COPY app/ .
COPY tests/ .

COPY Docker/wait-for-it.sh .

RUN chmod +x wait-for-it.sh

CMD ["./wait-for-it.sh", "db:5432", "--", "pytest"]

